<?php

/**
 * Implements hook_schema().
 */
function favorite_team_ctools_plugin_directory($module, $plugin) {
  //Ctools exportables ?
  if ($plugin == 'export_ui') {
    //assign de folder of ctools plugins files relative to module root
    return 'plugins/export_ui';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function favorite_team_form_user_profile_form_alter(&$form, &$form_state) {
  $account = $form['user'];

  //Get teams
  $teams = favorite_team_load_teams();
  $team_options = array();
  foreach ($teams as $team) {
    $team_options[$team->name] = $team->name;
  }

  $form['teams_fieldset'] = array(
    '#type' => 'fieldset',
    '#title' => t('Teams'),
  );
  $form['teams_fieldset']['teams'] = array(
    '#type' => 'checkboxes',
    '#title' => t('User Teams'),
    '#options' => $team_options,
    '#default_value' => isset($account->teams) ? array_keys($account->teams) : array(),
    );
}

/**
 * Implement load teams .
 */
function favorite_team_load_teams(){
  ctools_include('export');
  $result = ctools_export_load_object('team','all');
  return $result;
}

/**
 * Implements hook_user_update().
 */
function favorite_team_user_update(&$edit, $account, $category) {
  if (isset($edit['teams'])){
    //delete all teams
    db_delete('team_user')
      ->condition('uid',$account->uid)
      ->execute();
    //save new badges
    $query = db_insert('team_user')->fields(array('team','uid'));
    foreach ($edit['teams'] as $team => $value) {
      if ($value !== 0){
        $query->values(array('team'=>$team, 'uid' => $account->uid));
      }
    }
    $query->execute
  }
}

/**
 * Implements hook_user_load().
 */
function favorite_team_user_load($users) {
  /*
   *$result = db_query('SELECT * FROM {my_table} WHERE uid IN (:uids)', array(':uids' => array_keys($users)));
   *foreach ($result as $record) {
   *  $users[$record->uid]->foo = $result->foo;
   *}
   */
  /* Your code here */
}

/**
 * Implements hook_user_view().
 */
function favorite_team_user_view($account, $view_mode, $langcode) {
  /*
   *if (user_access('create blog content', $account)) {
   *  $account->content['summary']['blog'] =  array(
   *    '#type' => 'user_profile_item',
   *    '#title' => t('Blog'),
   *    '#markup' => l(t('View recent blog entries'), "blog/$account->uid", array('attributes' => array('title' => t("Read !username's latest blog entries.", array('!username' => format_username($account)))))),
   *    '#attributes' => array('class' => array('blog')),
   *  );
   *}
   */
  /* Your code here */
}

